version: '3.1'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: docker-compose.env
    ports:
      - "80:80"
    secrets:
      - privkey.pem
    restart: unless-stopped

secrets:
  privkey.pem:
    file: secrets/privkey.pem