version: '3.1'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: docker-compose.env
    ports:
      - "8080:8080"
    restart: unless-stopped